version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
       - sam package --template-file template.yaml --output-template-file outputsamTemplate.yaml --s3-bucket demo-ongraph
       - sam package --template-file template.yaml --output-template-file outputsamTemplate.yaml --s3-bucket codepipeline-eu-west-2-582809705180
       - sam package --template-file template.yaml --output-template-file outputsamTemplate.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1tum516a0jtw7
artifacts: 
  type: zip 
  files:
    - template.yaml
    - outputsamTemplate.yaml 
