version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:    
       - sam package --template-file template.yaml --output-template-file outputsamTemplate.yaml --s3-bucket arn:aws:s3:::aws-sam-cli-managed-default-samclisourcebucket-s7uit7nlkzc
artifacts: 
  type: zip 
  files:
    - template.yaml
    - outputsamTemplate.yaml 
