version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
       - aws cloudformation package --template-file template.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-s7uit7nlkzc --output-template-file outputsamTemplate.yaml
       - sam package --template-file template.yaml --output-template-file outputsamTemplate.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-s7uit7nlkzc
artifacts: 
  type: zip 
  files:
    - template.yaml
    - outputsamTemplate.yaml 
