version: 0.2
phases: 
  install:
     commands:
       - aws cloudformation package --template-file template.yaml --s3-bucket demo-ongraph --output-template-file packaged-template.yml
artifacts: 
  type: zip 
  files:
     - template.yaml
     - packaged-template.yml
    
    
