version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:    
       - chmod +x deploy.sh
       - ./deploy.sh
artifacts: 
  type: zip 
  files:
    - template.yaml
    - outputsamTemplate.yaml 
