version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "y"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-117s7cv99vs5x"
s3_prefix = "y"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "VersionParam=\"v1\" StageNameParam=\"prod\" CognitoDomainName=\"ongraph-demo\" Repository=\"\" Branch=\"master\""
image_repositories = []
